### ISSUE TITLE
DahuaVTO2MQTT ERROR

### ISSUE THREAD

**Issue by Lecturer555** [elad-bar/Hassio-addons#1]
Hello! there is such a problem, I don't know how to solve it, the addon does not want to be installed (
![Screenshot_72](https://user-images.githubusercontent.com/65249491/96478434-59478b80-1240-11eb-914d-0c535b76ccd9.png)
![Screenshot_73](https://user-images.githubusercontent.com/65249491/96478438-5a78b880-1240-11eb-9c91-5da2d88e3e4d.png)
![Screenshot_74](https://user-images.githubusercontent.com/65249491/96478439-5a78b880-1240-11eb-993e-ffa63ac7e4b7.png)

**Comment by Lecturer555** [comment]
Help with solution please!

**Comment by elad-bar** [comment]
For now, my suggestion is to use the docker directly,
During the weekend I'll try to set up test env. to reproduce it (I'm running HA core)

**Comment by jacobhopkins117** [comment]
Thank you for the work on this @elad-bar. I have the module installed in Docker via Portainer as a workaround for now.

**Comment by elad-bar** [comment]
restored v1.0.5 dockerfile without the file I renamed, I hope that now it will work,
if it doesn't, not sure how to handle it

please let me know

thanks

**Comment by ngreis** [comment]
updated to 1.0.8 with no errors, then when restarting the addon after update it fails with this error.
![image](https://user-images.githubusercontent.com/6894826/97930930-77df7380-1d64-11eb-9ec8-6ddf62ac685d.png)

had to restore snapshot of the addon at 1.0.5
