### ISSUE TITLE
Dahua Camera Compability

### ISSUE THREAD

**Issue by HappySl0th** [elad-bar/Hassio-addons#11]
Can this add on work with Dahua camera event such as line crossing?

**Comment by elad-bar** [comment]
didn't test it, you can try and share :)

**Comment by HappySl0th** [comment]
I currently have a VTO system and it is working well. Just wondering do i just enter another intercom tree?

intercom:
  host: 192.168.0.XX
  ssl: false
  username: admin
  password: password
mqtt:
  host: 192.168.0.XX
  port: '1883'
  username: admin
  password: password
  topic_prefix: DahuaVTO

**Comment by elad-bar** [comment]
Not sure I understand

**Comment by HappySl0th** [comment]
The above configuration is in my Home Assistant Addon for my doorbell. I am trying to add an additional camera for it to communicate with Home Assistant, however I am not sure how to get the camera into this addon.

**Comment by elad-bar** [comment]
Addon can be installed just once, install it using docker directly to have multiple instances
