### ISSUE TITLE
Password in configuration

### ISSUE THREAD

**Issue by philochardbleu** [elad-bar/Hassio-addons#13]
Hi!
Trying to settle the VTO2MQTT nice addon configuration, I have a password for the VTO which include a special character ( @ ) and it is not considered as valid in YAML. Is this normal ?
Thank you !

**Comment by elad-bar** [comment]
Can you please try to wrap it with quotation marks?

```yaml
password: "p@ssw0rd"
```

**Comment by philochardbleu** [comment]
That's perfect ! Thank you !

**Comment by elad-bar** [comment]
Great, thanks for the update
