### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by bombastikk** [elad-bar/Hassio-addons#15]
Hi 

Can you help i getting this error when i try install 

The command '/bin/ash -o pipefail -c apk update && apk upgrade && apk add --no-cache python3 py3-pip py3-setuptools git && pip3 install --upgrade pip --no-cache-dir paho-mqtt requests' returned a non-zero code: 3

**Comment by JordiPF** [comment]
Same trouble. Please help.

**Comment by jgrandar** [comment]
Same here

**Comment by 23Frodo** [comment]
I also have the same problem

**Comment by elad-bar** [comment]
I no longer maintain that repo as I don't own Hassio, instead there is dahuavto2mqtt docker container separately
