### ISSUE TITLE
Error when install

### ISSUE THREAD

**Issue by blademckain** [elad-bar/Hassio-addons#2]
When i try to install this component in hassio i get this error:

``
Failed to install addon
The command '/bin/ash -o pipefail -c apk add --no-cache --update argon2-libs php php-json && apk add --no-cache --virtual .build-dependencies git && git clone https://github.com/elad-bar/DahuaVTO2MQTT.git --branch ${DAHUA_BRANCH} --depth 1 /app && mv /app/DahuaEventHandler.php /app/DahuaVTO.php && chmod +x /app/DahuaVTO.php && apk del .build-dependencies' returned a non-zero code: 1
``

i think the problem is that the script try to launch this command:
``
 mv /app/DahuaEventHandler.php /app/DahuaVTO.php
``

but no app folder e no DahuaEventHandler.php file exists

**Comment by elad-bar** [comment]
Updated the addon, can you please check and let me know if iy works for you?
I'm using HA core so I can't test itthanks

**Comment by blademckain** [comment]
no
now this error:

``
The command '/bin/ash -o pipefail -c apk add --no-cache --update argon2-libs php php-json && apk add --no-cache --virtual .build-dependencies git && apk add --update libzip-dev curl-dev && docker-php-ext-install curl && apk del gcc g++ && rm -rf /var/cache/apk/* && git clone https://github.com/elad-bar/DahuaVTO2MQTT.git --branch ${DAHUA_BRANCH} --depth 1 /app && chmod +x /app/DahuaVTO.php && apk del .build-dependencies' returned a non-zero code: 14
``

**Comment by elad-bar** [comment]
Dup #1
