### ISSUE TITLE
Error During Install

### ISSUE THREAD

**Issue by IskenderKarfakis** [elad-bar/Hassio-addons#3]
Hi,

I'm getting this error when I try to install the latest addon 1.0.7 version

"Failed to install addon

The command '/bin/ash -o pipefail -c apk add --no-cache --update argon2-libs php php-json && apk add --no-cache --virtual .build-dependencies git && apk add --update libzip-dev curl-dev && docker-php-ext-install curl && apk del gcc g++ && rm -rf /var/cache/apk/* && git clone https://github.com/elad-bar/DahuaVTO2MQTT.git --branch ${DAHUA_BRANCH} --depth 1 /app && chmod +x /app/DahuaVTO.php && apk del .build-dependencies' returned a non-zero code: 14
"

System:
Raspberry 4 (4GB) aarch64
Home Assistant : 0.116.4
HassOS : 5.2
os_name : Linux
os_version : 4.19.127-v8
python_version : 3.8.5
supervisor : 249
docker_version : 19.03.11

**Comment by elad-bar** [comment]
Dup #1
