### ISSUE TITLE
HassOS 1.0.7 Installation Error

### ISSUE THREAD

**Issue by jacobhopkins117** [elad-bar/Hassio-addons#4]
Hello, 

I previously had version 1.0.6 installed, upon upgrading to 1.0.7 I received this error.

`Image 26703e67/amd64-addon-dahuavto2mqtt not exists for addon_26703e67_dahuavto2mqtt`

I uninstalled and reinstalled the add on and now I receive this error: 

 `The command '/bin/ash -o pipefail -c apk add --no-cache --update argon2-libs php php-json && apk add --no-cache --virtual .build-dependencies git && apk add --update libzip-dev curl-dev && docker-php-ext-install curl && apk del gcc g++ && rm -rf /var/cache/apk/* && git clone https://github.com/elad-bar/DahuaVTO2MQTT.git --branch ${DAHUA_BRANCH} --depth 1 /app && chmod +x /app/DahuaVTO.php && apk del .build-dependencies' returned a non-zero code: 3`

or 

`The command '/bin/ash -o pipefail -c apk add --no-cache --update argon2-libs php php-json && apk add --no-cache --virtual .build-dependencies git && apk add --update libzip-dev curl-dev && docker-php-ext-install curl && apk del gcc g++ && rm -rf /var/cache/apk/* && git clone https://github.com/elad-bar/DahuaVTO2MQTT.git --branch ${DAHUA_BRANCH} --depth 1 /app && chmod +x /app/DahuaVTO.php && apk del .build-dependencies' returned a non-zero code: 14`

I'm running my hassOS installation on a vmware virtual machine. 
Supervisor: 249
HassOS 4.15

**Comment by elad-bar** [comment]
Dup #1
