### ISSUE TITLE
Failed to install addon

### ISSUE THREAD

**Issue by emorosgit** [elad-bar/Hassio-addons#5]
Failed to install addon

The command '/bin/ash -o pipefail -c apk add --no-cache --update argon2-libs php php-json && apk add --no-cache --virtual .build-dependencies git && apk add --update libzip-dev curl-dev && docker-php-ext-install curl && apk del gcc g++ && rm -rf /var/cache/apk/* && git clone https://github.com/elad-bar/DahuaVTO2MQTT.git --branch ${DAHUA_BRANCH} --depth 1 /app && chmod +x /app/DahuaVTO.php && apk del .build-dependencies' returned a non-zero code: 14

**Comment by dimitrichko** [comment]
Same here

**Comment by elad-bar** [comment]
dup #1
