### ISSUE TITLE
Uncaught Error: Call to undefined function curl_init()

### ISSUE THREAD

**Issue by emorosgit** [elad-bar/Hassio-addons#6]
[13:59:14] INFO: Staring Dahua to MQTT
2020-11-03 12:59:14	<*** Dahua VTO Event Listener START ***>
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /app/DahuaVTO.php:106
Stack trace:
#0 /app/DahuaVTO.php(91): DahuaVTOAPI->SetDeviceDetails()
#1 /app/DahuaVTO.php(179): DahuaVTOAPI->DahuaVTOAPI()
#2 /app/DahuaVTO.php(9): DahuaVTOEventListener->DahuaVTOEventListener()
#3 {main}
  thrown in /app/DahuaVTO.php on line 106
[cmd] /bin/ash exited 255
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------

**Comment by dmitrychepel** [comment]
use https://github.com/dmitrychepel/Hassio-addons (or https://github.com/jbleuzen/Hassio-addons ) until this will be fixed.

**Comment by elad-bar** [comment]
@dmitrychepel I applied your fix, can you please let me know if it works for you?

thanks

**Comment by IskenderKarfakis** [comment]
After updating the addon to 1.0.9 I can confirm it works on my Raspberry Pi 4.
Thank you very much appreciated.

**Comment by emorosgit** [comment]
Yes, it works! Thanks!

**Comment by elad-bar** [comment]
Please update to the latest, should work now,
Thanks
