### ISSUE TITLE
/app/run.sh: line 19: python: command not found

### ISSUE THREAD

**Issue by arcidodo** [elad-bar/Hassio-addons#8]
Add-on version: 1.0.10
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[18:39:06] ERROR: Unknown HTTP error occured
 System:   (amd64 / qemux86-64)
 Home Assistant Core: 2020.12.2
 Home Assistant Supervisor: 2020.12.7
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[18:39:06] INFO: @@@@@@@@@@@@@@@@
/usr/bin/curl
[18:39:06] INFO: @@@@@@@@@@@@@@@@
[18:39:06] INFO: FFS
[18:39:06] INFO: Staring Dahua to MQTT
/app/run.sh: line 19: python: command not found
[cmd] /bin/ash exited 127
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by nibblerrick** [comment]
Same here.

**Comment by elad-bar** [comment]
Please try again and let me know if it works for you, 
I updated the startup path and updated version to 1.0.11

thanks

**Comment by arcidodo** [comment]
same issue:


[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: DahuaVTO2MQTT
 Listens to events from Dahua VTO unit and publishes them via MQTT Message
-----------------------------------------------------------
 Add-on version: 1.0.11
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[19:02:01] ERROR: Unknown HTTP error occured
 System:   (amd64 / qemux86-64)
 Home Assistant Core: 2020.12.2
 Home Assistant Supervisor: 2020.12.7
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[19:02:02] INFO: @@@@@@@@@@@@@@@@
/usr/bin/curl
[19:02:02] INFO: @@@@@@@@@@@@@@@@
[19:02:02] INFO: FFS
[19:02:02] INFO: Staring Dahua to MQTT
/app/run.sh: line 19: python: command not found
[cmd] /bin/ash exited 127
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by elad-bar** [comment]
Once again please, sorry, I'm using HA core, I can't test it before posting the addon version

**Comment by nibblerrick** [comment]
Works now for me! Thanks!

**Comment by elad-bar** [comment]
Great, thanks
